// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCacTCkp8qO2pf1zFHK1k9GRddHXfYP9QU',
    appId: '1:242440576982:web:945cd5cd79cf976917ce77',
    messagingSenderId: '242440576982',
    projectId: 'wesynk-app',
    authDomain: 'wesynk-app.firebaseapp.com',
    storageBucket: 'wesynk-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxWfjDFSqfGN8PeClM-KoFB8-5TW-ZHyA',
    appId: '1:242440576982:android:dadf6d2daf840b2517ce77',
    messagingSenderId: '242440576982',
    projectId: 'wesynk-app',
    storageBucket: 'wesynk-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7dmoQTUdL3fZ8vyIugLqWG7jqehEOi94',
    appId: '1:242440576982:ios:039fb6b2afcb2c6f17ce77',
    messagingSenderId: '242440576982',
    projectId: 'wesynk-app',
    storageBucket: 'wesynk-app.firebasestorage.app',
    iosBundleId: 'com.wesynk.wesynk',
  );
}
